services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    env_file: .env
    networks:
      - web

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - web
      - dokploy-network

networks:
  web:
    driver: bridge
  dokploy-network:
    external: true