services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    env_file: .env
    networks:
      - web
      - dokploy-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - web
      - dokploy-network

networks:
  web:
    driver: bridge
  dokploy-network:
    external: true