name: Deploy via Dokploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Trigger Dokploy 1
      run: |
        curl -k -X POST https://srv-ai-apps.int.alpha-it-innovations.org/api/deploy/FLRGusi--QdRevMwRJV6u \
          -H "Content-Type: application/json" \
          -H "X-GitHub-Event: push" \
          -d '{ ... }'

    - name: Trigger Dokploy 2
      run: |
        curl -k -X POST https://srv-ai-apps.int.alpha-it-innovations.org/api/deploy/ttIhpb2X8TDnwloJT6Fz6 \
          -H "Content-Type: application/json" \
          -H "X-GitHub-Event: push" \
          -d '{ ... }'